### ISSUE TITLE
Error: object 'callback' not found

### ISSUE THREAD

**Issue by kvten** [panorauma/ODCdqa#1]
`Error: object 'callback' not found` after clicking "Run Checks"

**Comment by kvten** [comment]
From

```
DT::datatable(
   ...
   callback=(callback)
)
```

inside `render_check_table` function

**Comment by kenf1** [comment]
Fixed in ff659db5b8e4b1fd6f9bb46c54f710b7e3c8c6e7

**Comment by kenf1** [comment]
Fixed in ff659db5b8e4b1fd6f9bb46c54f710b7e3c8c6e7

**Comment by kvten** [comment]
Check results now present. Show info on table cell click is not working.
ff659db5b8e4b1fd6f9bb46c54f710b7e3c8c6e7

**Comment by kvten** [comment]
Show info on table cell click fixed in 23cdd41c5029ac3c10cdb23a3b1fcbd1c956a419
